apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: k-s-template
build:
  artifacts:
    - image: parkyes90/k8s-template/api-server
      context: services/api-server
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.py"
            dest: .
    - image: parkyes90/k8s-template/web-client
      context: services/web-client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.{ts,tsx}"
            dest: .
manifests:
  kustomize:
    paths:
      - k8s/services/api-server/overlays/local
      - k8s/services/web-client/overlays/local
      - k8s/ingresses/overlays/local
      - k8s/services/dashboard/overlays/local
